clc;
clear;

% Group 2 Parameters for task1.
c = -2.851;
d = 3.402;
p_c = 7;
n_c = 2;
p_d = 8;
n_d = 3;
p_o = 12;
n_o = 3;

% Parameter	Value
% Filter type	lowpass
% Cutoff freqs Fpass, Fstop [kHz]4.6, 5.9
% passband ripple [dB]	0.25
% Stopband attenuation [dB]	50
% I/O signal word length	10
% Fs	30 kHz

Fpass = 4.6; % kHz
Fstop = 5.9; % kHz
pass_ripple = 0.25;
att_stopband = 50;
word_len = 10;
Fs = 30; % kHz


% The following code is generated with filterDesigner

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 11-Nov-2025 15:38:05

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 30;  % Sampling Frequency

Fpass = 4.6;              % Passband Frequency
Fstop = 5.9;              % Stopband Frequency
Dpass = 0.014390163418;   % Passband Ripple
Dstop = 0.0031622776602;  % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
% end generated code

Hdq = dfilt.dffir;
quantized_len = 15;
Hdq.Numerator = fi(Hd.Numerator,1,quantized_len,quantized_len - 1);

fprintf('There are %d coeffients in the filter\n', length(b))
fprintf('The sp.n format of the coefficients is s%d.%d\n', quantized_len, quantized_len - 1)
fvtool(Hd, Hdq);


% The following code is generated with filterDesigner

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 12-Nov-2025 19:01:11

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 30;  % Sampling Frequency

Fpass = 4.6;             % Passband Frequency
Fstop = 5.9;             % Stopband Frequency
Dpass = 0.011512416822;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd2 = dfilt.dffir(b);
% end generated code

Hdq2 = dfilt.dffir;
quantized_len = 10;
Hdq2.Numerator = fi(Hd.Numerator,1,quantized_len,quantized_len - 1);

fprintf('There are %d coeffients in the filter\n', length(b))
fprintf('The sp.n format of the coefficients is s%d.%d\n', quantized_len, quantized_len - 1)
fvtool(Hd2, Hdq2);
