function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 12-Nov-2025 19:01:11

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 30;  % Sampling Frequency

Fpass = 4.6;             % Passband Frequency
Fstop = 5.9;             % Stopband Frequency
Dpass = 0.011512416822;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
